CREATE TABLE NETWORKS (
	ID INT PRIMARY KEY NOT NULL,
	NAME CHAR(100) NOT NULL,
	DESCRIPITION CHAR(500),
	CREATEDDATE DATE,
	UPDATEDDATE DATE,
	CREATEDBY CHAR(50),
	UPDATEDBY CHAR(50)
	
);


CREATE TABLE PACKAGES (
	ID INT PRIMARY KEY NOT NULL,
	NAME CHAR(100) NOT NULL,
	NETWORKS TEXT ARRAY NOT NULL,
	PRICE money NOT NULL,
	CREATEDDATE DATE,
	UPDATEDDATE DATE,
	CREATEDBY CHAR(50),
	UPDATEDBY CHAR(50)
	
);

CREATE TABLE SHOWS (
	ID INT PRIMARY KEY NOT NULL,
	TITLE CHAR(1000) NOT NULL,
	NETWORK TEXT NOT NULL,
	IMDB_RATING INTEGER NOT NULL,
	CREATEDDATE DATE,
	UPDATEDDATE DATE,
	CREATEDBY CHAR(50),
	UPDATEDBY CHAR(50)
	
);